### ISSUE TITLE
Output tag

### ISSUE THREAD

**Issue by fergardi** [tjko/jpegoptim#10]
Hello.

I'm having problems in order to set the default output path for assetic to jpegoptim images.

According to the official cookbook documentation, we must use:

```
filters:
    jpegoptim:
      bin: usr/bin/jpegoptim
      apply_to: "\.jpg$"
      strip_all: true
      max: 70
  twig:
    functions:
      jpegoptim: { output: myfolder/*.jpg }
```

And then call the function in a twig template as usual like:

```
<img class='image' src='{{ jpegoptim('bundles/mybundle/images/myimage.jpg') }}' alt='Image'>
```

But this doesn't work. The image assets go to my assetic/ folder instead.

However, if I use the alternate single-use with no configutarion tags:

```
{% image 'bundles/mybundle/images/myimage.jpg'
    filter='jpegoptim' output='/myfolder/myimage.jpg' %}
    <img src="{{ asset_url }}" alt="Image"/>
{% endimage %}
```

Then it works perfectly. The bad thing is that I need to specify the output folder in EVERY single image. What's the point of the configuration output tag then? I'm doing it wrong?

Thank you in advance.
